DM
firedrakeproject/petsc_petsc4py_sprint pull request #23
Opened 2023-03-28 17:35 UTC by Ig-dolci

2023-03-30 14:33 UTC, dham requested changes

2023-03-30 14:33 UTC, dham commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        petsc.DMCoarsenHookAdd
missing parameters documentation.

2023-03-30 16:26 UTC, Ig-dolci commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> -    def setKSPComputeOperators(self, operators, args=None, kargs=None):
operators type will be defined in KSP PR.

2023-03-30 18:04 UTC, Ig-dolci commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        petsc.DMAdaptMetric
Done.

2023-03-30 18:04 UTC, Ig-dolci commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        petsc.DMClearLabelValue
Done.

2023-03-30 18:10 UTC, ksagiyam requested changes

2023-03-30 18:10 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +            The `DM` label.
```suggestion
            The name of the `DMLabel`.
```

2023-03-30 18:10 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +            The equation part, or 0 is unused.
```suggestion
        value
            Indicate the region.
        part
            The equation part, or 0 is unused.
```

2023-03-31 07:37 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def getAuxiliaryVec(self, label: str | None = None, value: int | None = 0, part: int | None = 0) -> Vec:
        """Return an auxiliary vector for region.

        Not collective.

        Parameters
        ----------
        label
            The name of the `DMLabel`.
        value
            Indicate the region.
        part
            The equation part, or 0 is unused.

        See Also
        --------
        DM.getLabel, petsc.DMGetAuxiliaryVec

        """
```

2023-03-31 07:47 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def setField(self, index: int, Object field, label: str | None = None) -> None:
        """Set the discretization object for a given `DM` field.

        Logically collective.

        Parameters
        ----------
        index
            The field number.
        field
            The discretization object.
        label
            The name of the label indicating the support of the field, or `None` for the entire mesh, currently must be `None`.

        See Also
        --------
        petsc.DMSetField

        """
```

2023-03-31 07:48 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def getField(self, index: int) -> tuple[Object, None]:
        """Return the discretization object for a given `DM` field.
        
        Not collective.
        
        Parameters
        ----------
        index
            The field number.

        See Also
        --------
        petsc.DMGetField

        """
```

2023-03-31 07:50 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        return (field, None) # TODO REVIEW
```suggestion
        return (field, None)
```

2023-03-31 07:54 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +            The discretization object.
```suggestion
    def addField(self, Object field, label: str | None = None) -> None:
        """Add a field to a `DM` object.

        Logically collective.

        Parameters
        ---------
        field
            The discretization object.
        label
            The name of the label indicating the support of the field, or `None` for the entire mesh, currently must be `None`.
```

2023-03-31 07:55 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        Logically Collective
```suggestion
        Logically collective.
```

2023-03-31 08:00 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def copyFields(self, DM dm) -> None:
        """Copy the discretizations of this `DM` into another `DM`.

        Collective.

        Parameters
        ----------
        dm
            The `DM` that the fields are copied into.

        See Also
        --------
        petsc.DMCopyFields

        """
```

2023-03-31 08:08 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def copyDisc(self, DM dm) -> None:
        """Copy fields and discrete systems of a `DM` into another `DM`.

        Collective.

        Parameters
        ----------
        dm
            The `DM` that the fields and discrete systems are copied into.

        See Also
        --------
        petsc.DMCopyDisc

        """
```

2023-03-31 08:08 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        Not Collective
```suggestion
        Not collective.
```

2023-03-31 08:14 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def setVecType(self, vec_type: Vec.Type | str) -> None:
        """Set the type of vector.

        Logically collective.

        See Also
        --------
        Vec.Type, petsc.DMSetVecType

        """
```

2023-03-31 08:16 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def restoreGlobalVec(self, Vec vg) -> None:
        """Restore a global vector.

        Not collective.

        Parameters
        ----------
        vg
            The global vector.

        See Also
        --------
        petsc.DMRestoreGlobalVector

        """
```

2023-03-31 08:17 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        Not collective
```suggestion
        Not collective.
```

2023-03-31 08:24 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def globalToLocal(self, Vec vg, Vec vl, addv: InsertMode | None = None) -> None:
        """Update local vectors from global vector.

        Neighborwise collective.

        Parameters
        ----------
        vg
            The global vector.
        vl
            The local vector.
        addv
            `InsertMode.INSERT_VALUES` or `InsertMode.ADD_VALUES`.

        See Also
        --------
        petsc.DMGlobalToLocalBegin, petsc.DMGlobalToLocalEnd

        """
```

2023-03-31 08:31 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def localToLocal(self, Vec vl, Vec vlg, addv: InsertMode | None = None) -> None:
        """Map the values from a local vector to another local vector.

        Neighborwise collective.

        Parameters
        ----------
        vg
            The global vector.
        vl
            The local vector.
        addv
            `InsertMode.INSERT_VALUES` or `InsertMode.ADD_VALUES`.

        See Also
        --------
        petsc.DMLocalToLocalBegin, petsc.DMLocalToLocalEnd

        """
```

2023-03-31 08:32 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        Collective
```suggestion
        """Set a global vector that holds the coordinates.

        Collective
```

2023-03-31 08:37 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def setMatType(self, mat_type: Mat.Type | str) -> None:
        """Set matrix type to be used by `DM.createMat`.
        
        Logically collective.

        Parameters
        ----------
        mat_type
            The matrix type.

        Notes
        -----
        The option ``-dm_mat_type`` is used to set the matrix type.

        See Also
        --------
        petsc_options, petsc.DMSetMatType
        
        """
```

2023-03-31 08:42 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def createMassMatrix(self, DM dmf) -> Mat:
        """Return the mass matrix between this `DM` and the given `DM`.

        Collective.

        Parameters
        ----------
        dmf
            The second `DM`.

        See Also
        --------
        petsc.DMCreateMassMatrix

        """
```

2023-03-31 08:44 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def createInterpolation(self, DM dm) -> tuple[Mat,Vec]:
        """Return the interpolation matrix between this `DM` and the given `DM`.

        Collective.

        Parameters
        ----------
        dm
           The second, finer `DM`.

        See Also
        --------
        petsc.DMCreateInterpolation

        """
```

2023-03-31 19:21 UTC, ksagiyam submitted a review, later dismissed

2023-03-31 19:21 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """Return a `DM` object coarsed.
```suggestion
        """Coarsen this `DM` and return the coarsened `DM` hierarchy.
```

2023-03-31 19:21 UTC, ksagiyam commented on src/binding/petsc4py/src/petsc4py/PETSc/DM.pyx
> +        """
```suggestion
    def adaptLabel(self, label: str) -> DM:
        """Adapt a `DM` based on a `DMLabel`.

        Collective.
        
        Parameters
        ----------
        label
            The name of the `DMLabel`.

        See Also
        --------
        petsc.DMAdaptLabel

        """
```

2023-04-02 19:22 UTC, dham approved these changes

2023-04-02 19:32 UTC, merged